[package]
name = "oxidized_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls"] }
html_parser = { version = "0.7.0" }
teloxide = { version = "0.12", default-features = false, features = [
  "ctrlc_handler",
  "rustls",
  "auto-send",
] }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
